### ISSUE TITLE
problems found during validation with installation method 3

### ISSUE THREAD

**Issue by iamshnoo** [willkessler/jupytergraffiti#38] opened 2019-06-03 04:39 UTC
![image](https://user-images.githubusercontent.com/45921510/58776011-1999e880-85e6-11e9-954b-95c011ef69c3.png)

Using the docker image installation method works fine. But, when I try to do using the 3rd method of installation (in order to avoid docker), I get the above error on running ```jupyter nbextension enable graffiti_extension/main --user```. The previous steps of the installation went perfectly without any errors.

The error reads as follows :
```
Enabling notebook extension graffiti_extension/main...
      - Validating: problems found:
        - require?  X graffiti_extension/main
```

I do not know how to fix this, as I am a complete beginner. I would really appreciate any help if possible.

**Comment by tugceakin** [comment] 2019-06-07 05:16
I'm guessing you are running this command in the wrong directory. Can you see `graffiti_extension` folder when you do `ls`? Can you try to run that command inside `jupytergraffiti` folder? Not in the root level but here: https://github.com/willkessler/jupytergraffiti/tree/master/jupytergraffiti

**Comment by iamshnoo** [comment] 2019-06-07 06:59
The graffiti_extension folder is indeed there and it contains the main.js file. 
![image](https://user-images.githubusercontent.com/45921510/59085485-62baa700-891c-11e9-8b86-5ca4a660d34e.png)
<br>
And I can see see graffiti_extension  when doing ls.
![image](https://user-images.githubusercontent.com/45921510/59085591-be853000-891c-11e9-8b6c-c282c720e017.png)
<br>
But when I run ```jupyter nbextension enable graffiti_extension/main --user``` in the directory you specified, I still get the same error.
![image](https://user-images.githubusercontent.com/45921510/59085658-0441f880-891d-11e9-81f9-7a74d07c6539.png)
<br>

And here is proof that I have done the previous step as mentioned in the README. 
![image](https://user-images.githubusercontent.com/45921510/59085852-9d710f00-891d-11e9-88cc-b9c64cf92f78.png)

I would like to include another piece of information, if that might help in understanding the problem.
Even though the extension enable step is not working for me,
when I open a Jupyter notebook and run ```import jupytergraffiti```, the cell gets executed as seen below.
![image](https://user-images.githubusercontent.com/45921510/59086203-a31b2480-891e-11e9-95fe-1c6ddc6be5cb.png)
<br>
But a weird thing happens. The first code cell moves down, and on top of it a full-page white area is created as in the following image. It shows recording, when I click the ```show graffiti editor``` button, but no where in the page can I see the editor.
![image](https://user-images.githubusercontent.com/45921510/59086186-972f6280-891e-11e9-91bc-2ecdba093bf1.png)
<br>

Instead, at the bottom of the page, I can see the following skeleton of the editor.
![image](https://user-images.githubusercontent.com/45921510/59086392-3d7b6800-891f-11e9-9bda-075aa7bf0342.png)

**Comment by willkessler** [comment] 2019-06-08 03:27
It looks like you are installing on Windows? I'm not sure if `--symlink` works as advertised on Windows... I'll have to try it. But you could try installing without that flag, and only use `--user`. See if that helps.

One weird thing is your error transcript above is the double slashes in the paths. I don't know how that can happen. However, it does look like you've tried to install more than once since the error is telling you that a file exists. Maybe go and clean up that file/directory before you try re-installing.

<img width="1278" alt="2019-06-07_2032" src="https://user-images.githubusercontent.com/176268/59141541-a71d6580-8963-11e9-84d9-a981ec118a5e.png">

As far as using `import jupytergraffiti`, the blank screen you screen-shotted is caused by the extension being unable to load the Graffiti CSS file from Jupyter. I'd like to see a screenshot of your network panel, to see what path it's trying to resolve to get to the CSS file. I can't tell what browser you're using (Chrome? Firefox?) but you should look to see where it tries to load `graffiti.css` (and probably gets a 404 error).

**Comment by willkessler** [comment] 2019-06-08 03:49
You could also try a couple of other solutions. You may not have symlinks enabled on your windows system.

https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

```You can create symbolic links using the mklink command in a Command Prompt window as Administrator. To open one, locate the “Command Prompt” shortcut in your Start menu, right-click it, and select “Run as Administrator”.

On Windows 10’s Creators Update, you can use a normal Command Prompt window, without running it as an Administrator. However, to do this without an Administrator Command Prompt window, you must first enable Developer Mode from Settings > Update & Security > For Developers.
```

Alternatively, you could try installing Linux for Windows and put jupyter in there:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by iamshnoo** [comment] 2019-06-08 06:06
1. I am installing on Windows. ```--symlink``` does not naturally work unless I run my command prompt as Administrator. So, during installation, I did run it as admin and ran into this problem.( I think the entire issue is probably something to do with Windows.) Symlinks are enabled on my system. I know because I had to use symlinks for something in a different project in the past.
2. Here is a screenshot of the network panel. I am using Google Chrome. The 404 error you mentioned is at the bottom-right of the page.
![image](https://user-images.githubusercontent.com/45921510/59142120-8b9f7280-89d6-11e9-83ed-cebb4c86592d.png)

The path indicated mentions ```notebooks``` . So, I searched my system for the folder to get the complete path location. Here is the screenshot.
![image](https://user-images.githubusercontent.com/45921510/59142203-05842b80-89d8-11e9-89eb-7568de100689.png)

3. The weird part with paths having double backslashes in them is probably only a Windows-specific feature as discussed in this stackoverflow answer [here](https://stackoverflow.com/questions/15969608/what-is-the-difference-between-and-in-file-path).

4. I did the WSL method already. It works. I just wanted to see if there was any way, I could use jupytergraffiti directly in Windows. If it doesn't, I can always go back to docker, as that is way more hassle-free.

5. I also tried deleting the symlink and cleaning up all files, before I try to re-install as you suggested. But, same error. Ah well, atleast we tried :)

**Comment by iamshnoo** [comment] 2019-06-08 06:07
Another thing, I noted is the following.
![image](https://user-images.githubusercontent.com/45921510/59142804-20a76900-89e1-11e9-9adf-d67ca43cc831.png)
The nbextensions tab lists all the notebook extensions on my system and gives me the option to enable or disable them. Here, I see that graffiti_extension/main is marked as incompatible. Maybe it is due to the installation problem I am facing in Windows on my system? Or it might be an issue in general? Might be worth looking into it. So, I am mentioning it here.

**Comment by willkessler** [comment] 2019-06-08 14:18
I have a hunch what is causing the extension to not locate the css files.

We can investigate using a Windows VM. Please tell us what exact version of
Windows you're using though.

**Comment by iamshnoo** [comment] 2019-06-09 02:33
I am using Windows 10 Home edition.

**Comment by willkessler** [comment] 2019-06-09 20:18
OK well I believe I've identified the issue at least that's keeping `import jupytergraffiti` from working. I [check paths for forward slashes](https://github.com/willkessler/jupytergraffiti/blob/ed3328d130b05738ccca5ec95492cd40fb2625ad/jupytergraffiti/js/utils.js#L817), not reverse slashes. We can add some windows support to make it work.

**Comment by iamshnoo** [comment] 2019-06-10 02:48
That's great. Thank you for your support.

**Comment by willkessler** [comment] 2019-06-11 00:21
@iamshnoo 

I just installed JupyterGraffiti on a windows server 2019 edition system after installing anaconda. I did not change anything in the codebase, but everything installs and works. Here's the steps I took.

I installed anaconda using the installer I got from http://www.anaconda.com/distribution/#windows and installed Python 3.7 version. I did not use administrative privileges.

Then I did what's in the following screenshot:

<img width="1079" alt="windows_server_successful_installation_1" src="https://user-images.githubusercontent.com/176268/59234886-91967e80-8ba3-11e9-8228-cb4197eff20b.png">

 Spelled out, the steps I took were:

`jupyter nbextension install graffiti_extension --user`

then

`jupyter nbextension enable graffiti_extension/main --user`

then, of course

`jupyter notebook`

from the directory containing the `jupytergraffiti` directory.

Because this server was set up in google cloud, I did not have access to the microphone, so I could not make movie recordings, but nonetheless I was able to add a graffiti tip to a new notebook:

<img width="1056" alt="windows_server_successful_installation_2" src="https://user-images.githubusercontent.com/176268/59234992-16819800-8ba4-11e9-9bf2-8e9f4da10d9d.png">

**Comment by willkessler** [comment] 2019-06-11 01:21
My colleague @tugceakin pointed out that maybe the fact that you have already installed `jupyter_contrib_nbextension` might be the source of the trouble. To try to replicate, I started a new windows vm with anaconda installed, and did:

` pip install jupyter_contrib_nbextensions`

then

` jupyter contrib nbextension install --user`

and finally:

```
jupyter nbextension install graffiti_extension --user
 jupyter nbextension enable graffiti_extension/main --user
```

and everything also worked fine. So that's not your issue... I'm not sure what else to try to replicate your problem. The only thing I can think now is that something is different between Windows 10 Home and Windows Server.... not a Windows expert so, not sure what to suggest?

**Comment by iamshnoo** [comment] 2019-06-11 02:50
Could you try just one more thing in a separate new virtual machine with Windows and Anaconda installed (?) .  
Point is I did not initially have jupyter_contrib_nbextension installed when I first had the problem around the beginning of last week. I first had the problem. I tried a lot of things to resolve it. I opened this issue here. After a few days, I installed jupyter_contrib_nbextension. So, that wasn't the source of the problem, because the problem was there without it.
So, maybe you could(?) try just one last thing, which is to not install the jupyter_contrib_nbextension and instead directly install graffiti. If that works, it would mean something is wrong specific to my Windows 10 Home installation. If it doesn't, it might give a solution to the problem. (Probably this should work on the VM, as it already does in presence of jupyter_contrib_nbextension, but just for completeness in the replication, I am asking for this attempt.)

**Comment by willkessler** [comment] 2019-06-11 03:03
That was my first success, see the previous post. If you like you can get a
free account on Google compute, spin up a Windows server host, install
anaconda and give it a try. I'm also going to see if I can reproduce with
virtual box though.

**Comment by iamshnoo** [comment] 2019-06-11 03:27
Okay. I will try the GCP. Let me know how the virtual box thing works out. :)

**Comment by willkessler** [comment] 2019-06-11 03:47
Will do. But the virtualbox setup is Windows server again. Can't locate Home
Edition for virtual box yet

**Comment by willkessler** [comment] 2020-01-24 02:24
Can you try installing with `pip` or `conda` @iamshnoo ?

**Comment by iamshnoo** [comment] 2020-01-24 16:26
I tried the ```conda``` install and it worked like a charm. Here is a screenshot of the installation process completing perfectly.
![jupyter graffiti](https://user-images.githubusercontent.com/45921510/73085157-42b01600-3ef4-11ea-8783-e236728dd392.jpg)
Thank you for getting back to me on this issue.
We can finally close this thread now.

**Comment by willkessler** [comment] 2020-01-24 18:58
Excellent. Does recording videos work on Windows for you?

**Comment by iamshnoo** [comment] 2020-01-24 20:02
Oh! Forgot to check that first. But now that I do, I see there is an open issue on this. And yes, the problem persists on my machine too. 
So, I can record the graffiti as usual
![ss1](https://user-images.githubusercontent.com/45921510/73098909-5ec1b080-3f10-11ea-8167-91c231af7138.jpg)
But, when I click on play movie button, I see the error message
![ss2](https://user-images.githubusercontent.com/45921510/73098998-86b11400-3f10-11ea-9604-8df6a88d3cdb.jpg)
So, I tried to run Jupyter as Admin hoping that at least then it would believe that I am the author of the Notebook, but the problem persists.
Also, **(The default value is jupytergraffiti_data/, a folder in the same directory as this Notebook.) is a message that gets shown if I want to change the path of storing data**
So, I thought of checking the Notebook's directory to find that folder, but it isn't there.
There is only a file named graffiti_sample.txt.cr in the same folder as the notebook and nothing else related to graffiti.
This is a sample movie cell which I tried to use
![ss3](https://user-images.githubusercontent.com/45921510/73099784-39ce3d00-3f12-11ea-8707-ba0aa18dc357.jpg)
And this is the corresponding output stored in graffiti_sample.txt.cr
![ss4](https://user-images.githubusercontent.com/45921510/73099821-4c487680-3f12-11ea-92f7-8b79be9d17ed.jpg)

So, I guess it is not being able to form the folder for storing recordings due to the path-related issue in Windows.

**Comment by iamshnoo** [comment] 2020-01-24 20:05
Some specifics about my Windows version is included in the image below, so that you can try to reproduce the problem.
![ss5](https://user-images.githubusercontent.com/45921510/73100167-05a74c00-3f13-11ea-83f4-b474ca133189.jpg)

**Comment by willkessler** [comment] 2020-01-24 20:36
Great, this is very helpful. I will try to duplicate your setup on MS Azure to see how to debug it.

Can you paste here the steps you took to install Jupyter on your system, if you have them? That way i can follow that setup on Azure.

**Comment by iamshnoo** [comment] 2020-01-24 22:51
I am not sure of the exact steps I took, because I created the current conda environment some time back. But, here is a list of stuff which I most probably did back then.

1. Install Miniconda.
2. Install VS Code.
3. Create a conda environment xyz with python 3 ( note that this is one of many environments I have on my system, I have installed graffiti only in this environment, but Jupyter Notebook is installed in many of the different environments )
4. conda install some packages I needed for a project (numpy, matplotlib, scikit-learn, seaborn, pandas)
5. conda install jupyter
6. conda installation command for Jupyter graffiti (tried this a few hours back when you commented on this issue)

This is the exact environment which I have right now. If I access Jupyter Notebook from VS code, I don't see anything for the graffiti extension (This might be a separate issue from the on we are trying to solve). So, I tried it out by launching  Jupyter from a local Host Port in Google Chrome. I believe I have the latest version of Chrome installed.

Also, just as a note,
Compared to the environment I had around June, the current one does not have any fancy packages or add-ons installed other than the ones I listed above.

**Comment by willkessler** [comment] 2020-02-25 05:58
Hello @iamshnoo !

If you are still interested, you can now install Graffiti with pip and it will work in Windows 10+ systems. 

I'm still working on updating the Conda installation to support WIndows, not sure why it's not working right now.

If you get a few minutes to try it out, I'd appreciate it. Just do

`pip install jupytergraffiti`

Cheers

**Comment by iamshnoo** [comment] 2020-02-26 06:15
I just tried the pip installation and then recorded a demo video as well. It worked perfectly this time. Finally! Thank you so much for taking out time to resolve this issue even if it took so long.

**Comment by willkessler** [comment] 2020-02-26 06:27
Great. Closing this issue. Thanks for the feedback, and spread the word about Graffiti!

**Closed as completed by willkessler** 2020-02-26 06:27 UTC
